spring.application.name=medical-online-store
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
spring.datasource.url=jdbc:mysql://localhost:3306/medical_store
spring.datasource.username=root
spring.datasource.password=root/uvpassword9969

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true